language: android

jdk: oraclejdk8

notifications:
  email:
    recipients: muxter.matao@gmail.com
    on_success: never
    on_failure: always

sudo: false

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.3
    - android-25
    - sys-img-armeabi-v7a-android-25

  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_script:
  - chmod +x gradlew

  # Emulator Management: Create, Start and Wait
  - echo no | android create avd --force -n test -t android-25 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew :example:installDebug
