language: android
jdk: oraclejdk8
cache: false
sudo: false

notifications:
  email:
    recipients: muxter.matao@gmail.com
    on_success: never
    on_failure: always

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.3
    - android-25

  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_script:
  - chmod +x gradlew

script:
  - ./gradlew :example:assembleDebug
